trigger:
- master
pr:
- master

jobs:
- job:
  displayName: Run Linting and Tests
  pool:
    vmImage: 'ubuntu-16.04'

  variables:
    azure_tmpdir: $(Agent.TempDirectory)
    devtools: $(azure_tmpdir)/devtools
    test_dir: src/testing

  container: prlmushr/mushr:bionic

  steps:
  - script: git clone https://github.com/prl-mushr/devtools.git $(devtools)
    displayName: Get devtools

  - bash: /ros_entrypoint.sh $(devtools)/bin/mushr_lint_flake8 .
    displayName: flake8
    condition: succeededOrFailed()

  - bash: /ros_entrypoint.sh $(devtools)/bin/mushr_lint_isort . --check
    displayName: isort
    condition: succeededOrFailed()

  - bash: /ros_entrypoint.sh $(devtools)/bin/mushr_lint_black . --check
    displayName: black
    condition: succeededOrFailed()

  - bash: |
      apt-get update && apt-get install --no-install-recommends -y python-tk
      mkdir -p /catkin_ws/src/$(Build.Repository.Name)
      cp -r * /catkin_ws/src/$(Build.Repository.Name)

      cd /catkin_ws
      /ros_entrypoint.sh catkin_make

      /ros_entrypoint.sh catkin_make run_tests
    displayName: Run tests
    condition: succeededOrFailed()
